services:
  n8n-main:
    image: n8nio/n8n:latest
    container_name: n8n-main
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - QUEUE_BULL_REDIS_HOST=${QUEUE_BULL_REDIS_HOST}
      - QUEUE_BULL_REDIS_PORT=${QUEUE_BULL_REDIS_PORT}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - EXECUTIONS_MODE=${EXECUTIONS_MODE}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_HOST=${N8N_HOST}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_ENDPOINT_REST=${N8N_ENDPOINT_REST}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_DEFAULT_LOCALE=${N8N_DEFAULT_LOCALE}
      - N8N_RUNNERS_ENABLED=true
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
    volumes:
      - n8n_data:/home/node/.n8n

  n8n-setup:
    image: curlimages/curl:latest
    container_name: n8n-setup
    depends_on:
      n8n-main:
        condition: service_started
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_OWNER_EMAIL=${N8N_OWNER_EMAIL}
      - N8N_OWNER_FIRST_NAME=${N8N_OWNER_FIRST_NAME}
      - N8N_OWNER_LAST_NAME=${N8N_OWNER_LAST_NAME}
      - N8N_OWNER_PASSWORD=${N8N_OWNER_PASSWORD}
    command: >
      /bin/sh -c '
        echo "等待 n8n-main 啟動...";
        sleep 60;
        echo "⏳ 建立 n8n Owner...";
        curl -s -X POST "${WEBHOOK_URL}/workflow/rest/owner/setup" \
          -H "Content-Type: application/json" \
          -d "{
            \"email\": \"${N8N_OWNER_EMAIL}\",
            \"firstName\": \"${N8N_OWNER_FIRST_NAME}\",
            \"lastName\": \"${N8N_OWNER_LAST_NAME}\",
            \"password\": \"${N8N_OWNER_PASSWORD}\"
          }";
      '

  n8n-import-auto:
    image: n8nio/n8n:latest
    container_name: n8n-import-auto
    working_dir: /workflows
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - ./workflows:/workflows
    entrypoint: []
    command: ["tail", "-f", "/dev/null"]

volumes:
  n8n_data:
